schema_version: 1

context:
  name: google-genai
  version: "1.12.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/google_genai-${{ version }}.tar.gz
  sha256: 5c7eda422360643ce602a3f6b23152470ec1039310ef40080cbe4e71237f6391

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
    - twine >=6.1.0
  run:
    - python >=${{ python_min }}
    - anyio >=4.8.0,<5.0.0dev
    - google-auth >=2.14.1,<3.0.0dev
    - httpx >=0.28.1,<1.0.0dev
    - pydantic >=2.0.0,<3.0.0dev
    - requests >=2.28.1,<3.0.0dev
    - websockets >=13.0.0,<15.1.0dev

tests:
  - python:
      imports:
        - google.genai
        - google.genai.types
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: GenAI Python SDK
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/python-genai

extra:
  recipe-maintainers:
    - hadim
